AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description:
  Nested stack for DE3 team project

Resources:
  Extract:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./extract/template.yaml

  Transform:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./transform/template.yaml
    DependsOn: Extract

  Load:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./load/template.yaml
    DependsOn: Transform

  Alarm:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./alarm/template.yaml
    DependsOn: Load

  Workflow:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./workflow/template.yaml
    DependsOn: Alarm
