AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to query Redshift and send alerts to Slack

Resources:
  SlackAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./alarm
      Timeout: 60
      MemorySize: 128
      VpcConfig:
        SubnetIds:
          - !ImportValue RedshiftPublicSubnet1Id
          - !ImportValue RedshiftPublicSubnet2Id
          - !ImportValue RedshiftPublicSubnet3Id
        SecurityGroupIds:
          - !ImportValue SecurityGroupId
      Environment:
        Variables:
          SLACK_WEBHOOK_PATH: "/services/T070MKQ7CJY/B07G10BC7U3/nRkzmVy5QIxTxwgWvc1R6i4x"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - redshift-data:ExecuteStatement
              Resource: "*"

Outputs:
  SlackAlertFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt SlackAlertFunction.Arn
    Export:
      Name: SlackAlertFunctionArn
