AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12

  SAM Template for extract

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:

  ExtractResults:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: de3-extract

  ExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TZ: 'Asia/Seoul'
      MemorySize: 2048
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
                - s3-object-lambda:*
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - s3-object-lambda:WriteGetObjectResponse
              Resource: '*'
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./extract
      DockerTag: python3.12-v1

Outputs:
  ExtractFunctionArn:
    Description: ARN of the Extract Lambda function
    Value: !GetAtt ExtractFunction.Arn
    Export:
      Name: ExtractFunctionArn