AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  This template deploys VPC and the required roles and to run the EMR cluster.
Resources:
  EMRAssetsS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'spark-transient-emr-lambda-${AWS::Region}-${AWS::AccountId}'
    DeletionPolicy: Delete

  EMRAssetS3BucketBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref EMRAssetsS3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt
                - EMRAssetsS3Bucket
                - Arn
              - !Join
                - ''
                - - !GetAtt
                    - EMRAssetsS3Bucket
                    - Arn
                  - /*
        Version: 2012-10-17

Outputs:
  EMRAssetsS3BucketName:
    Description: S3 bucket for EMR
    Value: !Ref EMRAssetsS3Bucket
    Export:
      Name: EMRAssetsS3BucketName

